version: '2.2'

services:
  web:
    build: .
    container_name: uvicorn
    command: uvicorn echo_api_integration_profiles:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./requests:/build/app/requests
    ports:
      - 80:80
